USE [STEFANINIFOODDB]
GO

INSERT INTO [DBO].[TB_USUARIO]([NOME],[CPF],[DATA_NASCIMENTO],[TELEFONE],[EMAIL],[SENHA])
VALUES      ('VITOR PINHEIRO MELO','12345678910','13-11-2001','971834529','VITOR@EMAIL.COM','123456');

INSERT INTO [DBO].[TB_USUARIO]([NOME],[CPF],[DATA_NASCIMENTO],[TELEFONE],[EMAIL],[SENHA])
VALUES      ('RUBENS FARIA','98765432145','27-05-1995','975834529','TESTE@EMAIL.COM','123456');

INSERT INTO [DBO].[TB_USUARIO]([NOME],[CPF],[DATA_NASCIMENTO],[TELEFONE],[EMAIL],[SENHA])
VALUES      ('LUANA SILVA','12345987675','16-01-1997','947351298','TESTE2@EMAIL.COM','123456');

INSERT INTO [DBO].[TB_USUARIO]([NOME],[CPF],[DATA_NASCIMENTO],[TELEFONE],[EMAIL],[SENHA])
VALUES      ('LUANA SILVA','12345987656','16-01-1997','947351298','TESTE3@EMAIL.COM','123456');

 
SELECT * FROM TB_USUARIO;


INSERT INTO [dbo].[TB_ENDERECO]([LOGRADOURO],[COMPLEMENTO],[CEP],[UF],[CIDADE],[ID_USUARIO])
     VALUES	('Rua Teste 1','Casa 1','12345678','SP','São Paulo', 1);
	 SELECT @@IDENTITY AS 'Identity';  


INSERT INTO [dbo].[TB_ENDERECO]([LOGRADOURO],[COMPLEMENTO],[CEP],[UF],[CIDADE],[ID_USUARIO])
     VALUES	('Rua Teste 2','Casa 2','87654321','SP','São Paulo', 1);

INSERT INTO [dbo].[TB_ENDERECO]([LOGRADOURO],[COMPLEMENTO],[CEP],[UF],[CIDADE],[ID_USUARIO])
     VALUES	('Rua Teste 3','Casa 3','12348765','SP','São Paulo', 2);

INSERT INTO [dbo].[TB_ENDERECO]([LOGRADOURO],[COMPLEMENTO],[CEP],[UF],[CIDADE],[ID_USUARIO])
     VALUES	('Rua Teste 4','Casa 4','87651234','SP','São Paulo', 3);

SELECT * FROM TB_ENDERECO;

INSERT INTO [dbo].[TB_PAGAMENTO]([APELIDO],[NUMERO],[CVV],[NOME_TITULAR],[ID_USUARIO])
	 VALUES ('CARTAO 1','XXX XXXX XXXX XXXX','XXX','Vitor Pinheiro Melo',1);

SELECT * FROM TB_PAGAMENTO;

INSERT INTO [dbo].[TB_CATEGORIA]([NOME],[DESCRICAO])
	 VALUES ('Refrigerante','Bebida gaseificada');

INSERT INTO [dbo].[TB_CATEGORIA]([NOME],[DESCRICAO])
	 VALUES ('Acompanhamento','Acompanhamento para os pedidos');

INSERT INTO [dbo].[TB_CATEGORIA]([NOME],[DESCRICAO])
	 VALUES ('Hamburguer','Lanche com carne bovina');

SELECT * FROM TB_CATEGORIA;

INSERT INTO [dbo].[TB_PRODUTO]([NOME],[DESCRICAO],[PRECO])
	 VALUES ('Big Mac','Dois hambúrgueres', 10);

INSERT INTO [dbo].[TB_PRODUTO]([NOME],[DESCRICAO],[PRECO])
	 VALUES ('Whooper','Hambúrguer BK', 10);

INSERT INTO [dbo].[TB_PRODUTO]([NOME],[DESCRICAO],[PRECO])
	 VALUES ('Coca-cola','Ref. de noz de cola', 10);

SELECT * FROM TB_PRODUTO;

INSERT INTO [dbo].[TB_LOJA]([NOME],[DESCRICAO],[TELEFONE],[ID_USUARIO])
	 VALUES ('MC DONALDS','FAST FOOD', '11 9999-9999',3);

INSERT INTO [dbo].[TB_LOJA]([NOME],[DESCRICAO],[TELEFONE],[ID_USUARIO])
	 VALUES ('BURGUER KING','FAST FOOD', '11 8888-9999',2);

SELECT * FROM TB_LOJA;

INSERT INTO [dbo].[TB_PRODUTO_CATEGORIA]([ID_PRODUTO],[ID_CATEGORIA])
	 VALUES (1, 3);

INSERT INTO [dbo].[TB_PRODUTO_CATEGORIA]([ID_PRODUTO],[ID_CATEGORIA])
	 VALUES (2, 3);

INSERT INTO [dbo].[TB_PRODUTO_CATEGORIA]([ID_PRODUTO],[ID_CATEGORIA])
	 VALUES (3, 1);

INSERT INTO TB_PRODUTO_LOJA (ID_PRODUTO,ID_LOJA)
	 VALUES (1,1);

INSERT INTO TB_PRODUTO_LOJA (ID_PRODUTO,ID_LOJA)
	 VALUES (2,2);

INSERT INTO TB_PRODUTO_LOJA (ID_PRODUTO,ID_LOJA)
	 VALUES (3,1);

INSERT INTO TB_PRODUTO_LOJA (ID_PRODUTO,ID_LOJA)
	 VALUES (3,2);

SELECT * FROM TB_PRODUTO_LOJA
SELECT * FROM TB_LOJA

	 -- PRODUTOS COM SUAS CATEGORIAS
SELECT * FROM TB_PRODUTO_CATEGORIA PC
INNER JOIN TB_PRODUTO P ON PC.ID_PRODUTO = P.ID
INNER JOIN TB_CATEGORIA C ON PC.ID_CATEGORIA = C.ID

	-- PRODUTOS COM SUAS LOJAS
SELECT P.NOME AS [NOME PRODUTO], L.NOME AS [NOME LOJA], P.PRECO AS [PREÇO TABELA], PL.PRECO AS [PREÇO LOJA] FROM TB_PRODUTO_LOJA PL
INNER JOIN TB_PRODUTO P ON PL.ID_PRODUTO = P.ID
INNER JOIN TB_LOJA L ON PL.ID_LOJA = L.ID


INSERT INTO [dbo].[TB_PEDIDO]([DESCRICAO],[PRECO],[ID_LOJA],[ID_USUARIO],[ID_ENDERECO],[ID_PAGAMENTO])
	 VALUES ('COMBO',20, 1,1,1,1);

INSERT INTO [dbo].[TB_PEDIDO_PRODUTO]([ID_PEDIDO],[ID_PRODUTO],[PRECO_PRATICADO])
	 VALUES (1,1,10);

INSERT INTO [dbo].[TB_PEDIDO_PRODUTO]([ID_PEDIDO],[ID_PRODUTO],[PRECO_PRATICADO])
	 VALUES (1,3,10);

SELECT U.NOME,E.CEP FROM TB_ENDERECO E
INNER JOIN TB_USUARIO U ON TB_ENDERECO.ID_USUARIO = TB_USUARIO.ID


-- FUNCTIONS
SELECT [dbo].[ValidaEmail] ('vitor@teste.com')

SELECT [dbo].LOJAVENDE(1, 1)

SELECT * FROM [dbo].[EXISTEEMAIL] ('vitor@teste.com')

SELECT [dbo].[CHECAPEDIDO] (1,1,1)

-- STORED PROCEDURE
  EXECUTE [dbo].[INSERIRPEDIDO] 
   'PEDIDO TESTE 2'
  ,20
  ,1
  ,1
  ,1
  ,1
  ,2
  ,'1,3'

  -- VIEWS
SELECT * FROM VIEW_PEDIDOS
SELECT * FROM VIEW_PEDIDO_PRODUTOS WHERE ID_PEDIDO = 1
